apiVersion: apps/v1
kind: Deployment
metadata:
  name: faas-dispatch-6
  namespace: openfaas
  labels:
    app: faas-dispatch-6
spec:
  replicas: 1
  selector:
    matchLabels:
      app: faas-dispatch-6
  template:
    metadata:
      labels:
        app: faas-dispatch-6
    spec:
      # serviceAccountName: faas-dispatch-6
      containers:
      - name: faas-dispatch-6
        image: lolopop/faas-dispatch:latest
        imagePullPolicy: IfNotPresent
        env:
          - name: PROMETHEUS_URL
            value: "http://10.244.0.38:9090"
          - name: GATEWAY_URL
            value: "http://gateway.openfaas.svc.cluster.local:8080"
          - name: NATS_URL
            value: "http://10.244.0.35:4222"
          - name: LEVEL
            value: "6"
          - name: REDIS_URL
            value: "faas-redis-master.openfaas.svc.cluster.local:6379"
          - name: REDIS_PASS
            value: "Y7MkRCBORP"
          - name: REDIS_KEY
            value: "activeServiceFunctions"
        ports:
        - containerPort: 5000
          protocol: TCP
      nodeName: dragonlan05