apiVersion: apps/v1
kind: Deployment
metadata:
  name: faas-monitor
  namespace: openfaas
  labels:
    app: faas-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: faas-monitor
  template:
    metadata:
      labels:
        app: faas-monitor
    spec:
      serviceAccountName: faas-monitor
      containers:
      - name: faas-monitor
        image: lolopop/faas-monitor:latest
        imagePullPolicy: IfNotPresent
        env:
          - name: SCRAPE_PERIOD
            value: "30"
          - name: PROMETHEUS_URL
            value: "http://10.244.0.110:9090"
          - name: GATEWAY_URL
            value: "http://gateway.openfaas.svc.cluster.local:8080"
          - name: NATS_URL
            value: "http://10.244.0.105:4222"
          - name: NATS_SUBJECT
            value: "metrics"
      nodeName: dragonlan05