---
apiVersion: v1
kind: Service
metadata:
  name: gateway-provider
  namespace: "openfaas"
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8081"
  labels:
    app: openfaas
    component: gateway
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8081
      targetPort: http
      protocol: TCP
  selector:
    app: gateway
