version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080/

functions:
  my-function:
    lang: python
    handler: ./nats-function
    image: lolopop/nats-function:latest
    environment:
      NATS_ADDRESS: http://10.244.0.35:4222
      # 其他环境变量...
    annotations:
      topic: my-topic
      description: My OpenFaaS function