---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: openfaas
    component: faas-dispatch-4
  name: faas-dispatch-4
  namespace: "openfaas"
spec:
  type: ClusterIP
  ports:
    - port: 5000
      protocol: TCP
  selector:
    app: faas-dispatch-4
