apiVersion: apps/v1
kind: Deployment
metadata:
  name: faas-idler
  namespace: openfaas
  labels:
    app: faas-idler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: faas-idler
  template:
    metadata:
      labels:
        app: faas-idler
    spec:
      serviceAccountName: faas-idler
      containers:
      - name: faas-idler
        image: lolopop/faas-idler:latest
        imagePullPolicy: Always
        env:
          - name: INACTIVITY_DURATION
            value: "60" # 5 minutes
          - name: RECONCILE_INTERVAL
            value: "60"
          - name: PROMETHEUS_URL
            value: "http://10.244.0.38:9090"
          - name: GATEWAY_URL
            value: "http://gateway.openfaas.svc.cluster.local:8080"
      nodeName: dragonlan05