apiVersion: apps/v1
kind: Deployment
metadata:
  name: faas-scaling
  namespace: openfaas
  labels:
    app: faas-scaling
spec:
  replicas: 1
  selector:
    matchLabels:
      app: faas-scaling
  template:
    metadata:
      labels:
        app: faas-scaling
    spec:
      serviceAccountName: faas-scaling
      containers:
      - name: faas-scaling
        image: lolopop/faas-scaling:latest
        imagePullPolicy: IfNotPresent
        env:
          - name: SCALING_WINDOWS
            value: "30"
          - name: PROMETHEUS_URL
            value: "http://prometheus.openfaas.svc.cluster.local:9090"
          - name: GATEWAY_URL
            value: "http://gateway.openfaas.svc.cluster.local:8080"
          - name: NATS_URL
            value: "http://nats.openfaas.svc.cluster.local:4222"
          - name: METRICS_SUBJECT
            value: "metrics"
          - name: REQ_SUBJECT
            value: "image"
          - name: REDIS_URL
            value: "faas-redis-master.openfaas.svc.cluster.local:6379"
          - name: REDIS_PASS
            value: "Y7MkRCBORP"
      - name: faas-predict
        image: lolopop/faas-predict:latest
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 5000
      nodeName: dragonlan05